travis:
  secure:
    BINSTAR_TOKEN: GkfkjjNTdwKiDWfMItg8RdOcc07+eqhBtZtZS1ooLxzbqbwHOc/m5EKMH0QgT6wz2z8pKGEDqU0l/GzvyNhTgpMo7fBiEpqZ1NL+U/7K36YthiT5WN3g1+lR/D/CHHo7oy5PuyNXvh47U7eukpB9YP7YOVj5smeX++F4ToUn0EAhOisF4QXM5FM5YFi5Zpo6ZLC7/mD/udSBESLT/KHGCvWN4J+YT2J+fyIDQ3syzln9WBelZKe5XS6PhxdH3ZNMwpm3CyYUkKvUP0qoMd1Plfq5AahaVdq9HC+IJ7eXB3zejOCZAI5+X7pm41Bmqj2BattxT6sop9cqkNJklB17lr3DD3VWaplEXm9n1MadcM4gvDooWbvpR7eHdP7ERjjmupYVvLg/Qa1o4nhT4oyqX+i6Do28U0gl1MuY5WUBJi8KZm4tCj7BbBPHSwOHxZ2AeQD2ljmWselcjyf/VlS4WL8iU3kvhL2e8rt3u5Ek0nzdyr3PsadzRl9Fru3FlDh+/6i+WwfaPZXq89k0g6kIeX6H998d1EVFd4vuORQaSLGIgV+sPMIzwCPFIgJJzxWlt2q4coSzrWQ2B1iydQiNRb4Qsqi3pLYK7y7c/uv2xyZxhXnTZbL3zsf237JDcR+hUvYysPhlDKelalhVot5yzNDpH0lFi2oQvJVRrjvxxks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
